# Generated by Django 4.0.6 on 2022-08-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elybra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('subtitulo1', models.CharField(max_length=50, verbose_name='SubTitulo1')),
                ('contenido1', models.TextField(max_length=150, verbose_name='Contenido1')),
                ('subcontenido1', models.TextField(max_length=150, verbose_name='SubContenido1')),
                ('subtitulo2', models.CharField(max_length=50, verbose_name='SubTitulo2')),
                ('contenido2', models.TextField(max_length=150, verbose_name='Contenido2')),
                ('subcontenido2', models.TextField(max_length=150, verbose_name='SubContenido2')),
                ('subtitulo3', models.CharField(max_length=50, verbose_name='SubTitulo3')),
                ('contenido3', models.TextField(max_length=150, verbose_name='Contenido3')),
                ('subcontenido3', models.TextField(max_length=150, verbose_name='SubContenido3')),
                ('pie1', models.CharField(max_length=50)),
                ('detPie1', models.TextField(max_length=50)),
                ('pie2', models.CharField(max_length=50)),
                ('detPie2', models.TextField(max_length=50)),
                ('pie3', models.CharField(max_length=50)),
                ('detPie3', models.TextField(max_length=50)),
                ('pie4', models.CharField(max_length=50)),
                ('detPie4', models.TextField(max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
